version: "3"
services:
  app:
    build: .
    working_dir: /app
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - "/app/node_modules"
      - "./wwebjs_auth:/app/wwebjs_auth"
      - ".:/app"
